blank_issues_enabled: false
contact_links:
  - name: Retro Engine Modding Server
    url: https://dc.railgun.works/retroengine
    about: If you have any questions about the decompilation or want help with modding, ask here.
